services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Eniams\Bundle\GitProfilerBundle\BranchLoader\Cache\GitCacheLoader: '@eniams.branchloader.git_cache_loader'
    Eniams\Bundle\GitProfilerBundle\BranchLoader\GitFilePath: '@eniams.branchloader.git_file_path'
    Eniams\Bundle\GitProfilerBundle\BranchLoader\GitLoader:  '@eniams.branchloader.git_loader'
    Eniams\Bundle\GitProfilerBundle\BranchLoader\Manager\GitManager: '@eniams.branchloader.git_manager'

    eniams.branchloader.git_file_path:
        class: Eniams\Bundle\GitProfilerBundle\BranchLoader\GitFilePath
        arguments:
            $projectDir: '%kernel.project_dir%'

    eniams.branchloader.git_cache_loader:
        class: Eniams\Bundle\GitProfilerBundle\BranchLoader\Cache\GitCacheLoader
        arguments:
            - '@cache.app.simple'
            - '@eniams.branchloader.git_file_path'

    eniams.branchloader.git_loader:
        class: Eniams\Bundle\GitProfilerBundle\BranchLoader\GitLoader
        arguments:
            - '@eniams.branchloader.git_file_path'

    eniams.branchloader.git_manager:
        class: Eniams\Bundle\GitProfilerBundle\BranchLoader\Manager\GitManager
        arguments:
            - '@eniams.branchloader.git_cache_loader'
            - '@eniams.branchloader.git_loader'

    Eniams\Bundle\GitProfilerBundle\DataCollector\GitDataCollector:
        arguments:
            - '@eniams.branchloader.git_cache_loader'
            - '@eniams.branchloader.git_manager'
        tags:
            - { name: data_collector, template: '@GitProfiler/Collector/git_profiler.html.twig', id: 'eniams.git_data_collector' }
